services:

  devd:
    image: ghcr.io/jefftriplett/devd:latest
    command: --livewatch
    expose:
      - 8000
    init: true
    ports:
      - 8000:8000
    volumes:
      - .:/srv/jekyll

  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --drafts --force_polling --watch --port 4000
    environment:
      - BUNDLE_PATH=/usr/local/bundle
    expose:
      - 4000
    init: true
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:cached
      - ./.vendor/bundle:/usr/local/bundle:cached
